# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65252386ee6d92b2087c1dbb7ceac75beeedcd62ffcdc8108ac2718b49a3d3cab48025d19b79920d2d2de18933f8f3ecef62679fdc04801301a33901f449b004

test:
  secret_key_base: 63ff209be06838cd369c473edc3084ce126d57adbbc91732264cc260291d181b128a4f8f3ab6fd2df0789cae71508e1f66c30e38f67dbfa11df3eb720e6a3a49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
